name: Java CI with Gradle and VPS Deployment

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 with Gradle
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set JAVA_HOME for Gradle
        run: echo "export GRADLE_OPTS='-Dorg.gradle.java.home=${JAVA_HOME}'" >> $GITHUB_ENV

      - name: Print Current Directory
        run: |
          pwd
          ls
          cd paypro-android-backend
          pwd
          ls
      - name: Build with Gradle
        run: |
          cd paypro-android-backend
          ls
          chmod +x gradlew
          ./gradlew build
      - name: Deploy to VPS
        run: |
          ssh user@your-vps-ip "cd /path/to/your/app && git pull && ./gradlew bootRun"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
